### ISSUE TITLE
don't work anymore with 4D V19

### ISSUE THREAD

**Issue by bmaniet** [miyako/4d-plugin-apple-window-title-bar#1]
Hope you will fix because i use it and me and my customers loves windows without title bar !
![d564ce85cd573c014a2e35a2d1bec17b73d92adb](https://user-images.githubusercontent.com/39809461/115701347-fc9c6900-a367-11eb-9df0-841eabdf21c4.png)

**Comment by miyako** [comment]
I think it is by design.

v19 supports colour schemes (light or dark) and fills the title bar with the window background colour.

if you use the plugin in an object method and trace the code, you might see that the window flag `NSWindowStyleMaskFullSizeContentView` is working as before and 4D draws the content view (the form) at the top of the window as expected. but as soon as the debugger is closed 4D reverts to the standard behaviour and draws the content view below the title bar. in other words, 4D is over-riding the OS behaviour of `NSWindowStyleMaskFullSizeContentView`.

I can shift the content view up by 22 points (the height of the title bar) but then all active objects such as buttons will respond at the wrong position because in v19 expects the content view to be below the title bar and not overlapping with the title bar.

**Comment by miyako** [comment]
it's a bit weird but I think a workaround would be,

* make the window background transparent 
* accept an image as the window's layer

proof of concept:

<img width="222" alt="penguin" src="https://user-images.githubusercontent.com/1725068/115751717-67838980-a3d4-11eb-9f09-b3b667a97dba.png">

**Comment by bmaniet** [comment]
Thanks for your reply !

I think of transparent window as workaround

**Comment by bmaniet** [comment]
Yes I already have custom background color ( rect )

Just need a growing sag with the nice 3D effect of Big Sur


Thanks again, Miyako !

**Comment by bmaniet** [comment]
The trick doesn't work if window having title bar
For a window without title bar, i can simulate close button but not collapse or full screen !
[Sans titre 2.pdf](https://github.com/miyako/4d-plugin-apple-window-title-bar/files/6363275/Sans.titre.2.pdf)

**Comment by miyako** [comment]
no, the workaround requires changes to the plugin.

**Comment by miyako** [comment]
refactoring

https://github.com/miyako/4d-plugin-window-style
